const SET_PROPS = "PAGE_SET_PROPS_";
const SET_VIEWTYPE = "PAGE_SET_VIEWTYPE_";
const SET_SEARCH = "PAGE_SET_SEARCH_";
const SET_FILTERS = "PAGE_SET_FILTERS_";
const SET_FILTERS_ACTIVE = "PAGE_SET_FILTERS_ACTIVE_";
const SET_SELECTED = "PAGE_SET_SELECTED_";
const SET_QUERY = "PAGE_SET_QUERY_";
const SET_STATUS = "PAGE_SET_STATUS_";
const SET_ACTIVE = "PAGE_SET_ACTIVE_";
const SET_PROCESSING = "PAGE_SET_PROCESSING_";

export default {
    SET_PROPS,
    SET_VIEWTYPE,
    SET_SEARCH,
    SET_FILTERS,
    SET_FILTERS_ACTIVE,
    SET_SELECTED,
    SET_QUERY,
    SET_STATUS,
    SET_ACTIVE,
    SET_PROCESSING
}