const SET_PROPS = "PAGE_SET_PROPS";
const SET_VIEWTYPE = "PAGE_SET_VIEWTYPE";
const SET_SEARCH = "PAGE_SET_SEARCH";
const SET_FILTERS = "PAGE_SET_FILTERS";
const SET_FILTERS_ACTIVE = "PAGE_SET_FILTERS_ACTIVE";
const SET_SELECTED = "PAGE_SET_SELECTED";
const SET_QUERY = "PAGE_SET_QUERY";
const SET_STATUS = "PAGE_SET_STATUS";
const SET_ACTIVE = "PAGE_SET_ACTIVE";
const SET_PROCESSING = "PAGE_SET_PROCESSING";

export default {
    SET_PROPS,
    SET_VIEWTYPE,
    SET_SEARCH,
    SET_FILTERS,
    SET_FILTERS_ACTIVE,
    SET_SELECTED,
    SET_QUERY,
    SET_STATUS,
    SET_ACTIVE,
    SET_PROCESSING
}