const FETCH = "ENTITY_FETCH_"
const FETCH_SUCCESS = "ENTITY_FETCH_SUCCESS_"
const FETCH_ERROR = "ENTITY_FETCH_ERROR_"
const DELETE = "ENTITY_DELETE_"
const DELETE_SUCCESS = "ENTITY_DELETE_SUCCESS_"
const DELETE_ERROR = "ENTITY_DELETE_ERROR_"
const SET_STATUS = "ENTITY_SET_STATUS_"

export default {
    FETCH,
    FETCH_SUCCESS,
    FETCH_ERROR,
    DELETE,
    DELETE_SUCCESS,
    DELETE_ERROR,
    SET_STATUS
}