const CREATE = "ENTITY_CREATE"
const FETCH = "ENTITY_FETCH"
const DELETE = "ENTITY_DELETE"
const UPDATE = "ENTITY_UPDATE"
const SET_STATUS = "ENTITY_SET_STATUS"

export default {
    CREATE,
    FETCH,
    DELETE,
    UPDATE,
    SET_STATUS
}