
export const PRODUCTS_LOADING = "PRODUCTS_LOADING"
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR"
export const PRODUCTS_FETCH_SUCCES = "PRODUCTS_FETCH_SUCCES"

export const REMOVE_PRODUCT_SUCCES = "REMOVE_PRODUCT_SUCCES"

export const PRODUCTS_CREATED = "PRODUCTS_CREATED"
